### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by Vgonma** [lojacho/Catalog-of-my-things#20]
- Github project: https://github.com/dgcuenca/Catalog-of-my-things/projects/2
- Group members: 3 people.
- Assigned roles:
  - @Vgonma `Team member #1`
  - @dgcuenca `Team member #2`
  - @OsvaldoBC `Team member #3`

**Comment by Qoosim** [comment]
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job implement your kanban board for the group project :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Kanban board created. :heavy_check_mark: 
-  Tasks assigned among group members. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

- [ ] It is required that tasks must be distributed in a fair way such that no member of the group should be assigned with all the complex tasks in the group. This could be known by the number of points assigns to a task. From my review, I noticed that
-  @Vgonma has total number of points = 7 hours
-  @OsvaldoBC has total number of points = 15 hours
-  @dgcuenca has total number of points = 9 hours

Based on the requirement, this is not fair enough. No member of the group should have more than 4 points of difference to another member. Kindly assign all the complex tasks fairly among the team members.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Qoosim** [comment]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  Tasks distributed faily among team members. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lojacho** [comment]
Aprobed
